version: '3.8'

services:
  pet-tracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./target:/app/target  # Only needed if you're building outside Docker